name: Publish update
on: [push]

jobs:
  build:
    name: Build & publish
    env:
      DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Enable experimental Docker features
        run: |
            mkdir -p ~/.docker
            echo "{\"experimental\": \"enabled\"}" > ~/.docker/config.json
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: env.DOCKER_USERNAME
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build for x86_64
        run: |
            docker build -t discord-http-proxy-botnet:amd64 .
      - name: Build for aarch64
        run: |
            docker build --no-cache --build-arg RUST_TARGET=aarch64-unknown-linux-musl --build-arg MUSL_TARGET=aarch64-linux-musl --build-arg FINAL_TARGET=arm64v8 -t discord-http-proxy-botnet:armv8 .
      - name: Create manifest and push it
        if: env.DOCKER_USERNAME
        run: |
            docker tag discord-http-proxy-botnet:amd64 ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:amd64
            docker tag discord-http-proxy-botnet:armv8 ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:armv8
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:amd64
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:armv8
            docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:latest ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:amd64 ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:armv8
            docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/discord-http-proxy-botnet:latest
